import pygame
class CharacterAnims:
    def __init__(self) -> None:
        pass
    def Initialize(self,url="src/gamedata/character_animations/"):
        character_anim_url= url

        self.enemy_attack = []
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_0.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_1.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_2.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_3.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_4.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_5.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_6.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_7.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_8.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_9.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_10.PNG").convert_alpha())
        self.enemy_attack.append( pygame.image.load(character_anim_url+"A/A_11.PNG").convert_alpha())

        self.enemy_dodge=[]
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_0.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_1.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_2.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_3.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_4.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_5.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_6.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_7.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_8.PNG").convert_alpha())
        self.enemy_dodge.append(pygame.image.load(character_anim_url+"D/D_9.PNG").convert_alpha())

        self.enemy_guard=[]
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_0.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_0.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_1.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_1.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_2.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_2.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_3.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_3.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_4.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_4.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_5.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_5.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_6.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_6.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_6.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_6.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_6.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_6.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_7.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_7.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_8.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_8.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_9.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_9.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_10.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_10.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_11.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_11.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_12.PNG").convert_alpha())
        self.enemy_guard.append(pygame.image.load(character_anim_url+"G/G_12.PNG").convert_alpha())

        self.enemy_poke =[]
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_0.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_1.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_2.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_3.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_4.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_5.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_6.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_7.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_8.PNG").convert_alpha())
        self.enemy_poke.append(pygame.image.load(character_anim_url+"P/P_9.PNG").convert_alpha())

        self.enemy_guardbreak=[]
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_0.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_1.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_2.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_3.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_4.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_5.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_6.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_7.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_8.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_9.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_10.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_11.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_12.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_13.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_14.PNG").convert_alpha())
        self.enemy_guardbreak.append(pygame.image.load(character_anim_url+"GB/GB_15.PNG").convert_alpha())

        self.enemy_die=[]
        self.enemy_die.append(pygame.image.load(character_anim_url+"DIE/DIE_0.PNG").convert_alpha())
        self.enemy_die.append(pygame.image.load(character_anim_url+"DIE/DIE_1.PNG").convert_alpha())
        self.enemy_die.append(pygame.image.load(character_anim_url+"DIE/DIE_2.PNG").convert_alpha())
        self.enemy_die.append(pygame.image.load(character_anim_url+"DIE/DIE_3.PNG").convert_alpha())
        self.enemy_die.append(pygame.image.load(character_anim_url+"DIE/DIE_4.PNG").convert_alpha())
        self.enemy_die.append(pygame.image.load(character_anim_url+"DIE/DIE_5.PNG").convert_alpha())
        self.enemy_die.append(pygame.image.load(character_anim_url+"DIE/DIE_6.PNG").convert_alpha())
        self.enemy_die.append(pygame.image.load(character_anim_url+"DIE/DIE_7.PNG").convert_alpha())

        self.self_attack=[]
        self.self_attack.append(pygame.image.load(character_anim_url+"SELF/SA/SA_0.PNG").convert_alpha())
        self.self_attack.append(pygame.image.load(character_anim_url+"SELF/SA/SA_1.PNG").convert_alpha())
        self.self_attack.append(pygame.image.load(character_anim_url+"SELF/SA/SA_2.PNG").convert_alpha())
        self.self_attack.append(pygame.image.load(character_anim_url+"SELF/SA/SA_3.PNG").convert_alpha())
        self.self_attack.append(pygame.image.load(character_anim_url+"SELF/SA/SA_4.PNG").convert_alpha())
        self.self_attack.append(pygame.image.load(character_anim_url+"SELF/SA/SA_5.PNG").convert_alpha())
        self.self_attack.append(pygame.image.load(character_anim_url+"SELF/SA/SA_6.PNG").convert_alpha())

        self.self_guard=[]
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_0.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_1.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_2.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_3.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_4.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_5.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_5.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_5.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_5.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_5.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_6.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_7.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_8.PNG").convert_alpha())
        self.self_guard.append(pygame.image.load(character_anim_url+"SELF/SG/G_9.PNG").convert_alpha())

        self.self_poke=[]
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_0.PNG").convert_alpha())
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_1.PNG").convert_alpha())
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_2.PNG").convert_alpha())
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_3.PNG").convert_alpha())
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_4.PNG").convert_alpha())
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_5.PNG").convert_alpha())
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_6.PNG").convert_alpha())
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_7.PNG").convert_alpha())
        self.self_poke.append(pygame.image.load(character_anim_url+"SELF/SP/SP_8.PNG").convert_alpha())

anim_resource = CharacterAnims()